import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1774935613188 implements MigrationInterface {
    name = 'InitialSchema1774935613188'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "name" character varying NOT NULL, "name_ar" character varying NOT NULL, "description" text, "permissions" jsonb NOT NULL, "is_system" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "user_id" uuid NOT NULL, "language" character varying NOT NULL DEFAULT 'en', "theme" character varying NOT NULL DEFAULT 'light', "primary_color" character varying NOT NULL DEFAULT '#4F46E5', "font_size" character varying NOT NULL DEFAULT 'medium', "show_cost_in_p_o_s" boolean NOT NULL DEFAULT false, "default_printer" character varying, CONSTRAINT "UQ_458057fa75b66e68a275647da2e" UNIQUE ("user_id"), CONSTRAINT "REL_458057fa75b66e68a275647da2" UNIQUE ("user_id"), CONSTRAINT "PK_e8cfb5b31af61cd363a6b6d7c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."credit_payments_method_enum" AS ENUM('CASH', 'CARD', 'CREDIT', 'SPLIT', 'REFUND')`);
        await queryRunner.query(`CREATE TABLE "credit_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "credit_account_id" uuid NOT NULL, "amount" numeric(12,4) NOT NULL, "method" "public"."credit_payments_method_enum" NOT NULL DEFAULT 'CASH', "notes" text, "collected_by_id" uuid, "invoice_id" uuid, CONSTRAINT "PK_c8bf096041d9d988603b649ee33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."credit_accounts_status_enum" AS ENUM('ACTIVE', 'OVERDUE', 'SUSPENDED', 'SETTLED')`);
        await queryRunner.query(`CREATE TABLE "credit_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "customer_id" uuid NOT NULL, "credit_limit" numeric(12,4) NOT NULL DEFAULT '0', "current_balance" numeric(12,4) NOT NULL DEFAULT '0', "status" "public"."credit_accounts_status_enum" NOT NULL DEFAULT 'ACTIVE', "last_payment_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_279e6d8ce4b1067eb58cd09756e" UNIQUE ("customer_id"), CONSTRAINT "REL_279e6d8ce4b1067eb58cd09756" UNIQUE ("customer_id"), CONSTRAINT "PK_a81047fa386ce9ab9567c763d72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "name" character varying NOT NULL, "name_ar" character varying, "phone" character varying, "email" character varying, "national_id" character varying, "date_of_birth" date, "address" text, "notes" text, "is_active" boolean NOT NULL DEFAULT true, "loyalty_points" integer NOT NULL DEFAULT '0', "total_purchases" numeric(14,4) NOT NULL DEFAULT '0', "invoice_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "color" character varying, "icon" character varying, "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "inventory_id" uuid NOT NULL, "batch_number" character varying, "quantity" numeric(12,4) NOT NULL, "remaining_qty" numeric(12,4) NOT NULL, "cost" numeric(12,4) NOT NULL, "expiry_date" TIMESTAMP WITH TIME ZONE, "is_expired" boolean NOT NULL DEFAULT false, "purchase_item_id" uuid, CONSTRAINT "PK_55e7ff646e969b61d37eea5be7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "product_id" uuid NOT NULL, "quantity" numeric(12,4) NOT NULL DEFAULT '0', "reserved_qty" numeric(12,4) NOT NULL DEFAULT '0', "avg_cost" numeric(12,4) NOT NULL DEFAULT '0', "total_value" numeric(14,4) NOT NULL DEFAULT '0', "reorder_level" numeric(12,4) NOT NULL DEFAULT '0', "max_level" numeric(12,4), "last_purchase_date" TIMESTAMP WITH TIME ZONE, "last_sale_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_92fc0c77bab4a656b9619322c62" UNIQUE ("product_id"), CONSTRAINT "REL_92fc0c77bab4a656b9619322c6" UNIQUE ("product_id"), CONSTRAINT "PK_7b1946392ffdcb50cfc6ac78c0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "contact_name" character varying, "phone" character varying, "email" character varying, "address" text, "tax_number" character varying, "notes" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('PRICE_OVERRIDE', 'BELOW_COST_SALE', 'INVENTORY_ADJUST', 'CREDIT_SALE', 'CREDIT_PAYMENT', 'DISCOUNT_OVERRIDE', 'SETTING_CHANGE', 'PURCHASE_CREATED', 'REFUND_ISSUED', 'USER_LOGIN', 'USER_LOGOUT', 'RULE_TRIGGERED', 'INVOICE_VOIDED', 'MANAGER_APPROVAL')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "invoice_id" uuid, "purchase_id" uuid, "before" jsonb, "after" jsonb, "metadata" jsonb, "ip_address" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchases_status_enum" AS ENUM('DRAFT', 'POSTED', 'VOIDED')`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "purchase_number" character varying NOT NULL, "supplier_id" uuid, "created_by_id" uuid NOT NULL, "ref_number" character varying, "invoice_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "total_cost" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "grand_total" numeric(14,4) NOT NULL, "notes" text, "status" "public"."purchases_status_enum" NOT NULL DEFAULT 'POSTED', CONSTRAINT "UQ_502e02e26c34f20da14c1384486" UNIQUE ("purchase_number"), CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "purchase_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(12,4) NOT NULL, "free_quantity" numeric(12,4) NOT NULL DEFAULT '0', "unit_cost" numeric(12,4) NOT NULL, "total_cost" numeric(14,4) NOT NULL, "expiry_date" TIMESTAMP WITH TIME ZONE, "batch_number" character varying, "prev_qty" numeric(12,4) NOT NULL, "prev_avg_cost" numeric(12,4) NOT NULL, "new_avg_cost" numeric(12,4) NOT NULL, CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_unit_enum" AS ENUM('piece', 'box', 'strip', 'bottle', 'vial', 'tube', 'sachet')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "barcode" character varying, "barcode2" character varying, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "generic_name_en" character varying, "generic_name_ar" character varying, "category_id" uuid, "default_selling_price" numeric(12,4) NOT NULL, "min_selling_price" numeric(12,4), "margin" numeric(5,2) NOT NULL, "taxable" boolean NOT NULL DEFAULT true, "track_expiry" boolean NOT NULL DEFAULT false, "require_prescription" boolean NOT NULL DEFAULT false, "unit" "public"."products_unit_enum" NOT NULL DEFAULT 'piece', "units_per_pack" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "is_service" boolean NOT NULL DEFAULT false, "notes" text, "image_url" character varying, CONSTRAINT "UQ_adfc522baf9d9b19cd7d9461b7e" UNIQUE ("barcode"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "invoice_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(12,4) NOT NULL, "cost" numeric(12,4) NOT NULL, "suggested_price" numeric(12,4) NOT NULL, "selling_price" numeric(12,4) NOT NULL, "discount_pct" numeric(5,2) NOT NULL DEFAULT '0', "discount_amount" numeric(12,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL, "profit" numeric(14,4) NOT NULL, "is_below_cost" boolean NOT NULL DEFAULT false, "is_override" boolean NOT NULL DEFAULT false, "batch_id" uuid, "expiry_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_53b99f9e0e2945e69de1a12b75a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CASH', 'CARD', 'CREDIT', 'SPLIT', 'REFUND')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "invoice_id" uuid NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "amount" numeric(12,4) NOT NULL, "reference" character varying, "notes" text, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'COMPLETED', 'VOIDED', 'REFUNDED', 'CREDIT')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "invoice_number" character varying NOT NULL, "cashier_id" uuid NOT NULL, "customer_id" uuid, "subtotal" numeric(14,4) NOT NULL, "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_pct" numeric(5,2) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL, "total_cost" numeric(14,4) NOT NULL, "profit" numeric(14,4) NOT NULL, "profit_margin" numeric(5,2) NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'COMPLETED', "notes" text, "shift_id" uuid, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "username" character varying NOT NULL, "password_hash" character varying NOT NULL, "full_name" character varying NOT NULL, "full_name_ar" character varying, "is_active" boolean NOT NULL DEFAULT true, "pin_hash" character varying, "role_id" uuid NOT NULL, "last_login_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "cashier_id" uuid NOT NULL, "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "closed_at" TIMESTAMP WITH TIME ZONE, "opening_cash" numeric(12,4) NOT NULL DEFAULT '0', "closing_cash" numeric(12,4), "system_cash" numeric(12,4), "variance" numeric(12,4), "invoice_count" integer NOT NULL DEFAULT '0', "total_revenue" numeric(14,4) NOT NULL DEFAULT '0', "total_profit" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "status" character varying NOT NULL DEFAULT 'OPEN', CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "key" character varying NOT NULL, "value" jsonb NOT NULL, "is_locked" boolean NOT NULL DEFAULT false, "group" character varying NOT NULL DEFAULT 'general', "updated_by_id" uuid, CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sequences" ("id" SERIAL NOT NULL, "prefix" character varying NOT NULL, "year" integer NOT NULL, "last_value" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_00c622186bcc3a244e99b82bc1e" UNIQUE ("prefix", "year"), CONSTRAINT "PK_7c7f5d8c822411196242b89bc76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rules_type_enum" AS ENUM('SALE', 'INVENTORY', 'USER', 'CREDIT')`);
        await queryRunner.query(`CREATE TABLE "rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_by" uuid, "updated_by" uuid, "name" character varying NOT NULL, "name_ar" character varying, "description" text, "type" "public"."rules_type_enum" NOT NULL, "condition" jsonb NOT NULL, "action" jsonb NOT NULL, "priority" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "is_system" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_10fef696a7d61140361b1b23608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_payments" ADD CONSTRAINT "FK_31cf75464c05e025dc4fd5908f4" FOREIGN KEY ("credit_account_id") REFERENCES "credit_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_accounts" ADD CONSTRAINT "FK_279e6d8ce4b1067eb58cd09756e" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "batches" ADD CONSTRAINT "FK_42b34bdf49df7e2f6c446e9efd7" FOREIGN KEY ("inventory_id") REFERENCES "inventories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_92fc0c77bab4a656b9619322c62" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_5ff55fdc8025efdd59629849ecf" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_d93acce0f0f2ba15d90fbfbba82" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_d5fec047f705d5b510c19379b95" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_fa639f207b2f99db328ddb04c08" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_607211d59b13e705a673a999ab5" FOREIGN KEY ("purchase_id") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_5a76734b5eead0967cf6ee3abc0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_c07224a78c1fd5dcd38e91284c5" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_c07224a78c1fd5dcd38e91284c5"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_5a76734b5eead0967cf6ee3abc0"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_43694b2fa800ce38d2da9ce74d6"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_607211d59b13e705a673a999ab5"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_fa639f207b2f99db328ddb04c08"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_d5fec047f705d5b510c19379b95"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_d93acce0f0f2ba15d90fbfbba82"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_5ff55fdc8025efdd59629849ecf"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_92fc0c77bab4a656b9619322c62"`);
        await queryRunner.query(`ALTER TABLE "batches" DROP CONSTRAINT "FK_42b34bdf49df7e2f6c446e9efd7"`);
        await queryRunner.query(`ALTER TABLE "credit_accounts" DROP CONSTRAINT "FK_279e6d8ce4b1067eb58cd09756e"`);
        await queryRunner.query(`ALTER TABLE "credit_payments" DROP CONSTRAINT "FK_31cf75464c05e025dc4fd5908f4"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`DROP TABLE "rules"`);
        await queryRunner.query(`DROP TYPE "public"."rules_type_enum"`);
        await queryRunner.query(`DROP TABLE "sequences"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_unit_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TYPE "public"."purchases_status_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "inventories"`);
        await queryRunner.query(`DROP TABLE "batches"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "credit_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."credit_accounts_status_enum"`);
        await queryRunner.query(`DROP TABLE "credit_payments"`);
        await queryRunner.query(`DROP TYPE "public"."credit_payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "user_preferences"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
