export enum AuditAction {
  PRICE_OVERRIDE = 'PRICE_OVERRIDE',
  BELOW_COST_SALE = 'BELOW_COST_SALE',
  INVENTORY_ADJUST = 'INVENTORY_ADJUST',
  CREDIT_SALE = 'CREDIT_SALE',
  CREDIT_PAYMENT = 'CREDIT_PAYMENT',
  DISCOUNT_OVERRIDE = 'DISCOUNT_OVERRIDE',
  SETTING_CHANGE = 'SETTING_CHANGE',
  PURCHASE_CREATED = 'PURCHASE_CREATED',
  REFUND_ISSUED = 'REFUND_ISSUED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  RULE_TRIGGERED = 'RULE_TRIGGERED',
  INVOICE_VOIDED = 'INVOICE_VOIDED',
  MANAGER_APPROVAL = 'MANAGER_APPROVAL',
  EXCHANGE_PROCESSED = 'EXCHANGE_PROCESSED',
  WALLET_TOPUP = 'WALLET_TOPUP',
  WALLET_DEDUCTION = 'WALLET_DEDUCTION',

  // User management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Role management
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',

  // Shifts
  SHIFT_OPENED = 'SHIFT_OPENED',
  SHIFT_CLOSED = 'SHIFT_CLOSED',

  // Purchase/Invoice lifecycle
  PURCHASE_VOIDED = 'PURCHASE_VOIDED',
  INVOICE_CREATED = 'INVOICE_CREATED',

  // Expenses
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_UPDATED = 'EXPENSE_UPDATED',
  EXPENSE_DELETED = 'EXPENSE_DELETED',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',

  // Supplier management
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_PAYMENT_CREATED = 'SUPPLIER_PAYMENT_CREATED',

  // Branch management
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  STOCK_TRANSFER_CREATED = 'STOCK_TRANSFER_CREATED',
  STOCK_TRANSFER_APPROVED = 'STOCK_TRANSFER_APPROVED',
  STOCK_TRANSFER_COMPLETED = 'STOCK_TRANSFER_COMPLETED',
  STOCK_TRANSFER_REJECTED = 'STOCK_TRANSFER_REJECTED',

  // Medical services
  SERVICE_CREATED = 'SERVICE_CREATED',
  SERVICE_UPDATED = 'SERVICE_UPDATED',
  SERVICE_DELETED = 'SERVICE_DELETED',
  SERVICE_PERFORMED = 'SERVICE_PERFORMED',
}
