export enum NotificationType {
  LOW_STOCK = 'LOW_STOCK',
  NEAR_EXPIRY = 'NEAR_EXPIRY',
  OVERDUE_CREDIT = 'OVERDUE_CREDIT',
  SHIFT_REMINDER = 'SHIFT_REMINDER',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  EXPENSE_APPROVAL = 'EXPENSE_APPROVAL',
  TRANSFER_REQUEST = 'TRANSFER_REQUEST',
  SALE_ALERT = 'SALE_ALERT',
  CREDIT_ALERT = 'CREDIT_ALERT',
}

export enum NotificationSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}
